[behave]
stderr_capture = False
stdout_capture = False
log_capture = False
show_skipped = true

# Reverting to only Allure formatter for results
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure-results
